package com.hm.entityDummy;
// Generated Nov 20, 2017 12:40:00 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FilesUpload generated by hbm2java
 */
@Entity
@Table(name = "files_upload", catalog = "fileUpload")
public class FilesUpload implements java.io.Serializable {

	private Integer uploadId;
	private String fileName;
	private String filePath;

	public FilesUpload() {
	}

	public FilesUpload(String fileName, String filePath) {
		this.fileName = fileName;
		this.filePath = filePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "upload_id", unique = true, nullable = false)
	public Integer getUploadId() {
		return this.uploadId;
	}

	public void setUploadId(Integer uploadId) {
		this.uploadId = uploadId;
	}

	@Column(name = "file_name", length = 128)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_path", length = 128)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
